#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

cols=certok,domainok,passwd,mailrelay,mailrelayuser,mailrelaypassword
labels="Zertifikate,Domain,CA Password,Mail Relay Sever, Mail Relay User, Mail Relay Password";
json_writeheader "$cols" "$labels" "certok:bool,domainok:bool" "" "passwd:notempty";

certok=
if [ -f  $certcadir/ca.crt ]; then
    certok=true
fi

domainok=
mne_need_error
systemctl is-enabled mne_samba-ad-dc.service >/dev/null 2>&1
if [ "$?" = "0" ]; then
  domainok=true
fi

passwd=
mailrelaypassword=

eval $(cat /etc/postfix/sasl/passwd 2>/dev/null | awk '/^$|^#/{ next } { printf("mailrelay=\"%s\";mailrelayuser=\"%s\"", $1, gensub(/:.*/,"",1,$2)) }')
echo '  "values"  : ['
json_writedata "$certok" "$domainok" "$passwd" "$mailrelay" "$mailrelayuser" "$mailrelaypassword"
echo ' ] '
exit 0