#!/bin/bash

configdir=$projectroot/config
datadir=/opt/mne/data
logid=sbs

certbasedir="$projectroot/sbs/exec/shell/sbs/cert/"
domainbasedir="$projectroot/sbs/exec/shell/sbs/domain/"
netbasedir="$projectroot/sbs/exec/shell/sbs/network/"
apachebasedir="$projectroot/sbs/exec/shell/sbs/apache/"

DBHOST="localhost"
DB="sbsdb"