#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

vacols="country,state,city,org,orgunit,email,passwd,overwrite,rmkey,file,data"
labels="Land,Region,Stadt,Orgnisation,Org. Einheit,Email,Password,Überschreiben,Schlüssel löschen,Primärer CA,CA Daten";
json_writeheader "$vacols" "$labels" "" "" "passwd:notempty"

eval "declare -A values=$(ca_read)"

echo '  "values"  : ['
json_writedata "${values[C]}" "${values[ST]}" "${values[L]}" "${values[O]}" "${values[OU]}" "${values[emailAddress]}" "" "" "" "${values[file]}" ""
echo ']'

exit 0
