#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

exit_status=0 

if [ "$vaenabledInput" = "1" ]; then
    a2enmod "$vanameInput" >&$logfile 2>&1
    if [ $? != 0 ]; then
      echo "error in enable $vanameInput" 1>&2;
      exit_status=1 
    fi
else
    a2dismod "$vanameInput" >&$logfile 2>&1
    if [ $? != 0 ]; then
      echo "error in disable $vanameInput" 1>&2;
      exit_status=1 
    fi
fi

$apachereload 2>&1 >&$logfile
exit $exit_status
