#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

cols="name,enabled"
labels="Name,enabled"
json_writeheader "$cols" "$labels" "enabled:1";

echo '"values" : [ '
komma=
IFS='\n' readarray -t mods < <(set +f; ls -1 $apacherootdir/mods-available | sed -e 's/\.[^.]*$//g' | sort -u)

declare -A modsenabled
eval "$(set +f; ls -1 $apacherootdir/mods-enabled | sed -e 's/\.[^.]*$//g' |  awk '{ printf("modsenabled[\"%s\"]=true;\n", $1) }' )"

for name in "${mods[@]}"
do
    enabled=false
    if [ "${modsenabled[$name]}" = "true" ]; then
        enabled=true
    fi
    
   if [ "$vawcol" = "" ] || [ "$(compare "${!vawcol}" "$vawop" "$vawval")" = "1" ]; then
     echo "$komma" ' [ "'"$name"'", "'"$enabled"'" ]';
     komma=","
   fi
done

echo ' ]'

  
