#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

eval $(get_groupnames "$vashareInput")

mne_need_error
samba-tool group removemembers "$groupnameread" "$valoginInput_old" >&$logfile
samba-tool group addmembers "$groupnameread" "$valoginInput" >&$logfile

mne_need_error
samba-tool group removemembers "$groupname" "$valoginInput_old" >&$logfile

if [ "$varwInput" = "1" ]; then
  samba-tool group addmembers "$groupname" "$valoginInput" >&$logfile
fi
	