#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

cols="login,fullname,rw";
labels="Login,Benutzer,Schreibzugriff";
json_writeheader "$cols" "$labels" "rw:bool";

eval $(get_groupnames "$vashareInput_old")

declare -A rw
eval $(read_users "$groupnameread" "rd" "false")
eval $(read_users "$groupname" "rw" "true")

echo '  "values"  : ['
( for i in "${!rdlogin[@]}"; do echo $i; done ) | sort | \
  while read index
  do
    json_writedata "${rdlogin[$index]}" "${rdfullname[$index]}" "${rw[$index]}"
  done
echo ']'
