#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

eval $(get_groupnames "$vashareInput")

if [ "$varwInput" = "1" ]; then
  samba-tool group addmembers "$groupname" "$valoginInput" >&$logfile
else
  samba-tool group addmembers "$groupnameread" "$valoginInput" >&$logfile
fi

apachectl graceful >&$logfile 2>&$logfile
smbcontrol all reload-config >&$logfile 2>&$logfile
