#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

eval $(get_groupnames "$vashareInput")

samba-tool group addmembers "$groupnameread" "$valoginInput" >&$logfile

if [ "$varwInput" = "1" ]; then
  samba-tool group addmembers "$groupname" "$valoginInput" >&$logfile
fi
