#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

groupname="Mneshare $(Tolower $(hostname)) $(Tolower $vashareInput)"
groupnameread="$groupname Read"

samba-tool group addmembers "$groupnameread" "$valoginInput" >&$logfile

if [ "$varwInput" = "1" ]; then
  samba-tool group addmembers "$groupname" "$valoginInput" >&$logfile
fi
