#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

ids="device,addr,mask,broadcast,readtime";
labels="Schnittstelle,Addresse,Mask,Broadcast,Lesezeit";
json_writeheader "$ids" "$labels" "readtime:1000" "";

hostname=$(hostname)

prog='/inet[^6]/ { found=1; printf("addr=\"%s\";bcast=\"%s\";\n", $2, $4); }
      /inet6/    { found=1; printf("addr=\"%s\";bcast=\"\";\n", $2); }
      END        { if ( ! found ) printf("addr=\"\";bcast=\"\";\n"); } '

echo '  "values"  : ['
for device in `ls /sys/class/net`
do
  if [ "$device" != "lo" ]; then

    ip address show dev $device | awk "$prog" >&$logfile
    ip address show dev $device | awk "$prog" | \
    while read line
    do
       eval $line
       if [ "$addr" != "" ]; then
         mask=${addr#*/}
         addr=${addr%/*}
       fi
       json_writedata "$device" "$addr" "$mask" "$bcast" "$acttime";
     done
     json_komma=","
   fi
done

echo ']'

exit 0
