#!/bin/bash

. sbs/exec/config/allg
. $(dirname $BASH_SOURCE)/config/functions

disable=$(findtemplate network netplan_disable)
conf_single=$(findtemplate network netplan_single)

if [ -d "$cloudcfgdir" ] && [ ! -f "$cloudcfgdir/99-mne-disable-network-config.cfg" ]; then
  cp $disable $cloudcfgdir/99-mne-disable-network-config.cfg;
fi


conffile="$netplandir/00-mne-$vadeviceInput.yaml"
mv "$conffile" "$conffile.save"
echo "$vaconfigInput" > "$conffile"

mne_need_error 
echo | netplan try > /dev/null
if [ "$?" != "0" ]; then
  mv "$conffile.save" "$conffile"
  exit 1
fi
 
exit 0
