#!/bin/bash

PREFIX=sbstest

mkdir -p /opt/mne/docker/sbs/postgresql
mkdir -p /opt/mne/docker/sbs/samba
mkdir -p /opt/mne/docker/sbs/sogo
mkdir -p /opt/mne/docker/sbs/postfix
mkdir -p /opt/mne/docker/sbs/dovecot

#mv /var/lib/docker/volumes/$PREFIX""_postgres_data/_data/ /opt/mne/docker/sbs/postgresql/data

mv /var/lib/docker/volumes/$PREFIX""_config/_data/ /opt/mne/docker/sbs/config
mv /var/lib/docker/volumes/$PREFIX""_cert/_data/ /opt/mne/docker/sbs/cert

mv /var/lib/docker/volumes/$PREFIX""_samba_etc/_data/ /opt/mne/docker/sbs/samba/etc
mv /var/lib/docker/volumes/$PREFIX""_samba_lib/_data/ /opt/mne/docker/sbs/samba/lib

mv /var/lib/docker/volumes/$PREFIX""_sogo_web/_data/ /opt/mne/docker/sbs/sogo/web

mv /var/lib/docker/volumes/$PREFIX""_postfix_mail/_data/ /opt/mne/docker/sbs/postfix/mail
mv /var/lib/docker/volumes/$PREFIX""_postfix_spool/_data/ /opt/mne/docker/sbs/postfix/spool

mv /var/lib/docker/volumes/$PREFIX""_dovecot_mail/_data/ /opt/mne/docker/sbs/dovecot/mail
