#!/bin/bash

origdb=sbsdb
orighost=localhost
origuser=admindb
origport=5432

checkdb=esbsdb
checkhost=localhost
checkuser=admindb
checkport=5432
output=sbs.sql

. ../../dbsync/dbempty
psql --username=$origuser --host=$orighost $checkdb <<EOF >/dev/null 2>&1
DROP SCHEMA ext_sogo CASCADE;
EOF

version=`cat ../../installer/mnesbs/dist/version`

rm -f empty.sql
. ./empty/mk_empty > empty.sql
psql --username=$origuser --host=$orighost $checkdb < empty.sql > /dev/null
rm empty.sql

echo "-- Database Version: $version" > $output
pg_dump --username=$origuser --host=$orighost $checkdb | sed -e "/CREATE EXTENSION.*plpgsql/d" -e "/COMMENT ON EXTENSION plpgsql/d" >> $output
