#!/bin/bash 

origdb=sbsdborig
orighost=127.0.156.1
origport=5432
origuser=admindb
#origpass='geheim'

checkdb=sbsdb
checkhost=127.0.156.1
checkport=5432
checkuser=admindb
#checkpass='geheim'

if [ "$(id -u)" = "0" ]; then
    orighost=127.0.156.1
    checkhost=127.0.156.1
    export PGPASSWORD="trust"
fi

cus_schemas="$cus_schemas"

cd ../../dbsync;
. dbupdate
