#!/bin/bash

. ../dbcfg.orig

origdb=sbsdb
orighost=$develophost
origuser=admindb

checkdb=emptydb
checkhost=$develophost
allschemas=0
output=sbs.sql

echo -n "Password for admindb: "
stty -echo < /dev/tty
read origpass
stty echo < /dev/tty
echo

while [ $# -gt 0 ] ; do
  case $1 in
    -sdb)   origdb=$2; shift 2;;              # source db
    -shost) orighost=$2; shift 2;;            # source host
    -spass) origpass=$2; shift 2;;            # source password
    -ddb)   checkdb=$2; shift 2;;             # dest db
    -dhost) checkhost=$2; shift 2;;           # dest host
    -dpass) checkpass=$2; shift 2;;           # dest passwd
    -all)   allschema=1; shift 1;;            # nur datenbank leeren keine schemas droppen
    -o)     output=$2; shift 2;;              # augabe datei
    -ho)    hoaioutput=$2; shift 2;;          # augabe datei hoai
     *)     shift 1 ;;
  esac
done

rm -f $output

export PGPASSWORD=$origpass
psql --username=$origuser --host=$orighost $origdb << EOF
    DROP DATABASE $checkdb;
EOF

psql --username=$origuser --host=$orighost --set ON_ERROR_STOP=on $origdb << EOF
    CREATE DATABASE $checkdb 
        WITH OWNER = admindb 
        ENCODING = 'UTF8' 
        TABLESPACE = pg_default 
        TEMPLATE = template0 
        LC_COLLATE = 'C' 
        LC_CTYPE = 'C' 
        CONNECTION LIMIT = -1; 
EOF

if [ $? != 0 ]; then
    exit 1
fi

rm -f origdb.sql
pg_dump    --username=$origuser --host=$orighost --disable-triggers --format=c $origdb > origdb.sql
pg_restore --username=$origuser --host=$orighost --disable-triggers --schema-only --dbname=$checkdb < origdb.sql
pg_restore --username=$origuser --host=$orighost --disable-triggers --data-only   --dbname=$checkdb < origdb.sql
rm origdb.sql

psql --username=$origuser --host=$orighost $checkdb <<EOF >/dev/null 2>&1
DROP SCHEMA mne_application_save CASCADE;
EOF

all=
if [ "$allschemas" != "1" ]; then
  psql --username=$origuser --host=$orighost $checkdb <<EOF >/dev/null 2>&1
    DROP SCHEMA ext_sogo CASCADE;
EOF
else
    all="-all"
fi

rm -f empty.sql
./dbempty -dhost $orighost -spass $origpass -dpass $origpass -ddb $checkdb $all > empty.sql
psql --username=$origuser --host=$orighost $checkdb < empty.sql > /dev/null
rm empty.sql
 
version=`cat ../../../installer/mnesbs/dist/version`
echo "-- Database Version: $version" > $output
pg_dump --username=$origuser --host=$orighost $checkdb | sed -e "/CREATE EXTENSION.*plpgsql/d" -e "/COMMENT ON EXTENSION plpgsql/d" >> $output
