#!/bin/bash

. sbs/exec/config/allg
. $certbasedir/config/functions
. $netbasedir/config/functions

. $(dirname $BASH_SOURCE)/config/functions

dhcpconf4=$(findtemplate  domain dhcpd4.conf)
dhcpconf6=$(findtemplate  domain dhcpd6.conf)
dhcpupdate=$(findtemplate domain update-samba-dns.sh)
radvdconf=$(findtemplate  domain radvd.conf)

#cols="domaintyp,domain,workgroup,description,netdevice,admin,adminpassword,adminpassword2,primaryname,primaryaddr,dnsforwarder,dnssearch,dhcpstart,dhcpend,dhcpdns,dhcp6start,dhcp6end,dhcp6dns";
if [ "$vadescriptionInput" = "" ]; then
    vadescriptionInput="%h server (Samba,Nelson - technische Informatik)"
fi

udomain=$(echo "$vadomainInput"  | awk '{print toupper($0)}')
domaindn=$(echo "$vadomainInput" | sed -e "s/^/dc=/" -e "s/\./,dc=/g")

if [ "$vadomaintypInput" == "primary" ] || [ "$vadomaintypInput" == "second" ]; then

  check_dnspasswd $udomain
  mod_netpar "$vadomainInput" "$vanetdeviceInput" "$vadnsforwarderInput" "$vadnssearchInput"
  mod_dhcp "$vadhcpdnsInput" "$vadhcpstartInput" "$vadhcpendInput" "$vadhcp6dnsInput" "$vadhcp6startInput" "$vadhcp6endInput" \
           "$vadomainInput" "$vadnssearchInput" "" "" "nicht mehr relevant" \
           "$dhcpconf4" "$dhcpconf6" "$dhcpupdate" "$radvdconf"
fi

exit 0