#!/bin/bash

. sbs/exec/config/allg
. $netbasedir/config/functions
. $(dirname $BASH_SOURCE)/config/functions

mne_need_error
systemctl is-enabled samba-ad-dc.service 2>&1 >/dev/null
if [ "$?" = "0" ]; then

  if [ "$vadns_recordInput" != "$vadns_recordInput_old" ]; then
     echo '#mne_lang#Kann Adresstyp nicht ändern'
     exit 1
  fi

  info=$(samba-tool domain info 127.0.0.1)
  domain=$(echo "$info" | awk -v FS=: '/Domain/ { sub(/^[ \t]+/, "", $2); print $2 }')
  check_dnspasswd $domain
  
  get_netparam
  
  if [ "$vadns_recordInput" = "AAAA" ]; then
    mask="$(echo $daddr6 | cut -f2 -d/)"
  else
    mask="$(echo $daddr4 | cut -f2 -d/)"
  fi 
  
  get_reverse $vadns_recordInput_old $vaaddressInput_old $mask

  mne_need_error
  samba-tool dns delete $(hostname) $domain "$vanameInput_old" "$vadns_recordInput_old" "$vaaddressInput_old" --use-kerberos=required >&$logfile 2>&1
  if [ "$?" != "0" ]; then
    echo '#mne_lang# Kann Addresse nicht finden#' >&2
  fi
  
  if [ "$vadns_recordInput_old" = "AAAA" ] or [ "$vadns_recordInput_old" = "A" ]; then
    mne_need_error
    samba-tool dns delete $(hostname) $zone $raddr PTR "$vanameInput_old.$domain" --use-kerberos=required >&$logfile 2>&1
    if [ "$?" != "0" ]; then
      echo '#mne_lang# Kann Rückaddresse nicht finden#' >&2
    fi    
  fi

  get_reverse $vadns_recordInput $vaaddressInput $mask
  mne_need_error
  samba-tool dns add $(hostname) $domain "$vanameInput" "$vadns_recordInput" "$vaaddressInput" -k yes >&$logfile 2>&1
  if [ "$?" != "0" ]; then
    echo '#mne_lang# Kann Addresse nicht hinzufügen#'
    exit 1;
  fi
  
  if [ "$vadns_recordInput" = "AAAA" ] or [ "$vadns_recordInput" = "A" ]; then
     mne_need_error
    samba-tool dns add $(hostname) $zone $raddr PTR "$vanameInput.$domain" --use-kerberos=required >&$logfile 2>&1
    if [ "$?" != "0" ]; then
      echo '#mne_lang# Kann Rückaddresse nicht hinzufügen#'
      exit 1;
    fi
  fi    
  
  if [ "$vadns_recordInput" != "$vadns_recordInput" ]; then
  	dhcp_fix_del "$vanameInput_old" "$vadns_recordInput_old"
  fi
  dhcp_fix_mod "$vanameInput_old" "$vanameInput" "$vaaddressInput"  "$vamacInput" "$vafixInput" "$vacommentInput" "$vadns_recordInput"
  
  systemctl restart isc-dhcp-server
  systemctl restart isc-dhcp-server6
fi

exit 0