#!/bin/bash -x

. sbs/exec/config/allg
. $netbasedir/config/functions
. $(dirname $BASH_SOURCE)/config/functions

mne_need_error
systemctl is-enabled samba-ad-dc.service 2>&1 >/dev/null
if [ "$?" = "0" ]; then

  if [ "$vadns_recordInput" != "$vadns_recordInput_old" ]; then
     echo '#mne_lang#Kann Adresstyp nicht ändern'
     exit 1
  fi

  domain=$(samba-tool domain info 127.0.0.1 | awk -v FS=: '/Domain/ { sub(/^[ \t]+/, "", $2); print $2 }')
  if [ "$vadomainInput" = "" ]; then
    vadomainInput="$domain"
  fi
  check_dnspasswd $domain
  
  eval "$(get_reverse $vadns_recordInput_old $vaaddressInput_old)"

  mne_need_error
  samba-tool dns delete $(hostname) $vadomainInput "$vanameInput_old" "$vadns_recordInput_old" "$vaaddressInput_old" --use-kerberos=required >&$logfile 2>&1
  if [ "$?" != "0" ]; then
    echo '#mne_lang# Kann Addresse nicht finden#' >&2
  fi
  
  if [ "$vadns_recordInput_old" = "AAAA" ] || [ "$vadns_recordInput_old" = "A" ]; then
    mne_need_error
    samba-tool dns delete $(hostname) $zone $raddr PTR "$vanameInput_old.$vadomainInput" --use-kerberos=required >&$logfile 2>&1
    if [ "$?" != "0" ]; then
      echo '#mne_lang# Kann Rückaddresse nicht finden#' >&2
    fi    
  fi

 eval "$(get_reverse $vadns_recordInput $vaaddressInput)"
  mne_need_error
  samba-tool dns add $(hostname) $vadomainInput "$vanameInput" "$vadns_recordInput" "$vaaddressInput" --use-kerberos=required >&$logfile 2>&1
  if [ "$?" != "0" ]; then
    echo '#mne_lang# Kann Addresse nicht hinzufügen#' >&2
  fi
  
  if [ "$vadns_recordInput" = "AAAA" ] || [ "$vadns_recordInput" = "A" ]; then
     mne_need_error
    samba-tool dns add $(hostname) $zone $raddr PTR "$vanameInput.$vadomainInput" --use-kerberos=required >&$logfile 2>&1
    if [ "$?" != "0" ]; then
      echo '#mne_lang# Kann Rückaddresse nicht hinzufügen#' >&2
    fi
  fi    
  
  dhcp_fix_mod "$vanameInput_old" "$vanameInput" "$vaaddressInput"  "$vamacInput" "$vafixInput" "$vacommentInput" "$vadns_recordInput"
  
  systemctl restart isc-dhcp-server
  systemctl restart isc-dhcp-server6
fi

exit 0