#!/bin/bash

. sbs/exec/config/allg
. $netbasedir/config/functions
. $(dirname $BASH_SOURCE)/config/functions

mne_need_error
info=$(samba-tool domain info 127.0.0.1 2>/dev/null) 
if [ "$?" = "0" ]; then

  domain=$(echo "$info" | awk -v FS=: '/Domain/ { sub(/^[ \t]+/, "", $2); print $2 }')
  check_dnspasswd $domain
  
  mne_need_error
  samba-tool dns zonedelete $(hostname) "$vanameInput_old" --use-kerberos=required >&$logfile 2>&$logfile
  if [ "$?" != "0" ]; then
    echo '#mne_lang# Kann Zone nicht löschen#' >&2
    exit 1;
  fi    
fi

exit 0
